#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

# gaps["top"]="24"
# gaps["bottom"]="0"
# gaps["left"]="0"
# gaps["right"]="0"
# gaps["inner"]="0"

#color["focused"]="0xE0808080"
#color["normal"]="0x00010101"
#color["preselect"]="0xE02d74da"

RED="0x00010101"
BLUE="0xE0ffb3b4"

yabai -m config external_bar                all:24:25
# yabai -m config top_padding                 "${gaps["top"]}"
# yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                2
yabai -m config right_padding               2
yabai -m config window_gap                  1

yabai -m config layout                      bsp

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autofocus

yabai -m config window_topmost              on
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on 
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "${BLUE}"
yabai -m config normal_window_border_color  "${RED}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_drop_action             swap
yabai -m config mouse_modifer               alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# # ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

ignore="(系统偏好设置)"
yabai -m rule --add title="${ignore}" manage=off

yabai -m rule --add app=".*(NeteaseMusic|Spotify).*" space=3
yabai -m rule --add app=".*(Chrome|Firefox).*" space=2
yabai -m rule --add app=".*(Visual Studio|Term).*" space=1
